# Standard BIOS/MBR partition scheme: boot + swap + root
# Generated by flake-installer
{
  disko.devices = {
    disk = {
      main = {
        type = "disk";
        device = "{{DISK_DEVICE}}";
        content = {
          type = "gpt";
          partitions = {
            boot = {
              size = "1M";
              type = "EF02"; # BIOS boot partition
            };
            swap = {
              size = "{{SWAP_SIZE}}";
              content = {
                type = "swap";
                randomEncryption = true;
              };
            };
            root = {
              size = "100%";
              bootable = true;
              content = {
                type = "filesystem";
                format = "ext4";
                mountpoint = "/";
              };
            };
          };
        };
      };
    };
  };

  # BIOS boot configuration
  boot.loader.grub = {
    enable = true;
    device = "{{DISK_DEVICE}}";
    efiSupport = false;
  };
}
