# Standard UEFI partition scheme: ESP + swap + root
# Generated by flake-installer
{
  disko.devices = {
    disk = {
      main = {
        type = "disk";
        device = "{{DISK_DEVICE}}";
        content = {
          type = "gpt";
          partitions = {
            ESP = {
              size = "512M";
              type = "EF00";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot";
                mountOptions = ["defaults"];
              };
            };
            swap = {
              size = "{{SWAP_SIZE}}";
              content = {
                type = "swap";
                randomEncryption = true;
              };
            };
            root = {
              size = "100%";
              content = {
                type = "filesystem";
                format = "ext4";
                mountpoint = "/";
              };
            };
          };
        };
      };
    };
  };
}
